modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/MORIMORI0317/DangerousStoneCutter/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "dangerousstonecutter"
version = "${version}"
displayName = "Dangerous Stone Cutter"
updateJSONURL = "https://raw.githubusercontent.com/MORIMORI0317/DangerousStoneCutter/main/version_check.json"
authors = "MORIMORI0317"
description = '''
This mod makes the stone cutter dangerous.
The ikisugi stone cutter mod...
'''
logoFile = "icon.png"

[modproperties.dangerousstonecutter]
catalogueImageIcon = "icon.png"

[[dependencies.dangerousstonecutter]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dangerousstonecutter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"