org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true
# Mod properties
mod_version=1.9.0
maven_group=net.morimori0317
archives_name=DangerousStoneCutter
mod_id=dangerousstonecutter
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.1
support_versions=1.21.1
# Dependencies
architectury_api_version=13.0.8
fabric_loader_version=0.19.3
fabric_api_version=0.116.13+1.21.1
neoforge_version=21.1.235
# Upload
curesforge_id=345729
modrinth_id=jSFfBGeF
release_type=release
# Other
repository_url=https://github.com/MORIMORI0317/DangerousStoneCutter
