pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.minecraftforge.net/" }
        gradlePluginPortal()
    }
    plugins {
        id 'org.jetbrains.kotlin.jvm' version '2.4.0'
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}

include("common")
include("fabric")
include("neoforge")

rootProject.name = "DangerousStoneCutter"
