modLoader="javafml"
loaderVersion="[37,)"
license="LGPL v3"
[[mods]]
modId="dangerousstonecutter"
version="${file.jarVersion}"
displayName="Dangerous Stone Cutter"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dangerousstonecutter"
authors="MORIMORI0317"
description="Thank you for downloading!"
